export const effects = [
    {
      'id': 'forest',
      'title': 'Forest',
      'emoji': '🌲',
      'category': 'nature',
      'url':  '/sounds/forest.mp3',
    },
    {
      'id': 'bonfire',
      'title': 'Bonfire',
      'emoji': '🔥',
      'category': 'nature',
      'url':  '/sounds/bonfire.mp3',
    },
    {
      'id': 'rain',
      'title': 'Rain',
      'emoji': '🌧️',
      'category': 'nature',
      'url':  '/sounds/rain-gutter.mp3',
    },
    {
      'id': 'wind',
      'title': 'Forest wind',
      'emoji': '🌬️',
      'category': 'nature',
      'url':  '/sounds/windy_forest.mp3',
    },
    {
      'id': 'thunder',
      'title': 'Thunder',
      'emoji': '🌩️',
      'category': 'nature',
      'url':  '/sounds/thunder.mp3',
    },
    {
      'id': 'ocean_waves',
      'title': 'Waves',
      'emoji': '🌊',
      'category': 'nature',
      'url':  '/sounds/ocean_waves.mp3',
    },
    {
      'id': 'white_noise',
      'title': 'White noise',
      'emoji': '⬜️🔉',
      'category': 'nature',
      'url':  '/sounds/white_noise.mp3',
    },
    {
      'id': 'keyboard',
      'title': 'Keyboard',
      'emoji': '⌨️',
      'category': 'nature',
      'url':  '/sounds/keyboard.mp3',
    },
    {
      'id': 'fan',
      'title': 'Fan',
      'emoji': '📻',
      'category': 'nature',
      'url':  '/sounds/fan.mp3',
    },
    {
      'id': 'neighbourhood',
      'title': 'Neighbourhood',
      'emoji': '🏘️',
      'category': 'nature',
      'url':  '/sounds/neighbourhood.mp3',
    },
    {
      'id': 'coffee',
      'title': 'Coffee',
      'emoji': '🥘',
      'category': 'nature',
      'url':  '/sounds/outdoor.mp3',
    },
    // {
    //   'id': 'dock_waves_splash',
    //   'title': 'Waves splash',
    //   'emoji': '🌊⛴️',
    //   'category': 'nature',
    //   'url':  '/sounds/dock_waves_splash.mp3',
    // },

    // {
    //   'id': 'forest_footsteps',
    //   'title': 'Footsteps',
    //   'emoji': '🌲🥾',
    //   'category': 'nature',
    //   'url':  '/sounds/forest_footsteps.mp3',
    // },
    // {
    //   'id': 'grass_footsteps',
    //   'title': 'Footsteps',
    //   'emoji': '🌱🥾',
    //   'category': 'nature',
    //   'url':  '/sounds/grass_footsteps.mp3',
    // },
    // {
    //   'id': 'leaves_footsteps',
    //   'title': 'Footsteps',
    //   'emoji': '🍂🥾',
    //   'category': 'nature',
    //   'url':  '/sounds/leaves_footsteps.mp3',
    // },
    // {
    //   'id': 'snow_footsteps',
    //   'title': 'Footsteps',
    //   'emoji': '❄️🥾',
    //   'category': 'nature',
    //   'url':  '/sounds/snow_footsteps.mp3',
    // },

    // {
    //   'id': 'computer_fan',
    //   'title': 'Computer fan',
    //   'emoji': '🖥️💨',
    //   'category': 'office',
    //   'url':  '/sounds/computer_fan.mp3',
    // },
    // {
    //   'id': 'server_room',
    //   'title': 'Server',
    //   'emoji': '🏢 🖥️',
    //   'category': 'office',
    //   'url':  '/sounds/server-room.mp3',
    // },
    // {
    //   'id': 'train',
    //   'title': 'Train',
    //   'emoji': '🚂',
    //   'category': 'vehicle',
    //   'url':  '/sounds/train.mp3',
    // },
    // {
    //   'id': 'cow',
    //   'title': 'Cow',
    //   'emoji': '🐮',
    //   'category': 'animals',
    //   'url':  '/sounds/cow.mp3',
    // },
    // {
    //   'id': 'crickets',
    //   'title': 'Crickets',
    //   'emoji': '🦗',
    //   'category': 'nature',
    //   'url':  '/sounds/desert_night.mp3',
    // },
    // {
    //   'id': 'horse',
    //   'title': 'Horse',
    //   'emoji': '🐴',
    //   'category': 'nature',
    //   'url':  '/sounds/horse.mp3',
    // },

    // {
    //   'id': 'jungle_frogs',
    //   'title': 'Frogs',
    //   'emoji': '🐸',
    //   'category': 'animals',
    //   'url':  '/sounds/jungle_frogs.mp3',
    // },
    // {
    //   'id': 'nuclear_siren',
    //   'title': 'Nuclear siren',
    //   'emoji': '☢️',
    //   'category': 'alarm',
    //   'url':  '/sounds/nuclear_siren.mp3',
    // },
    // {
    //   'id': 'alarm_nuclear',
    //   'title': 'Alarm',
    //   'emoji': '⚠️',
    //   'category': 'alarm',
    //   'url':  '/sounds/alarm_nuclear_facility.mp3',
    // },
    // {
    //   'id': 'crowd_cheer',
    //   'title': 'Cheers',
    //   'emoji': '👏',
    //   'category': 'public',
    //   'url':  '/sounds/crowd_cheer.mp3',
    // },
    // {
    //   'id': 'basketball',
    //   'title': 'Basketball',
    //   'emoji': '🏀',
    //   'category': 'sports',
    //   'url':  '/sounds/basketball.mp3',
    // },
    // {
    //   'id': 'blood_drum',
    //   'title': 'Blood drums',
    //   'emoji': '🩸 🥁',
    //   'category': 'instruments',
    //   'url':  '/sounds/blood_drum.mp3',
    // },
    // {
    //   'id': 'tribal_drum',
    //   'title': 'Tribal drums',
    //   'emoji': '⛺🥁',
    //   'category': 'instruments',
    //   'url':  '/sounds/tribal_drum.mp3',
    // },
    // {
    //   'id': 'grand_prix',
    //   'title': 'Grand prix',
    //   'emoji': '🏎',
    //   'category': 'vehicle',
    //   'url':  '/sounds/grand_prix.mp3',
    // },
    // {
    //   'id': 'motor_race',
    //   'title': 'Motor race',
    //   'emoji': '🏍',
    //   'category': 'vehicle',
    //   'url':  '/sounds/motor_race.mp3',
    // },
    // {
    //   'id': 'ice_rink_refrig',
    //   'title': 'Ice refrig',
    //   'emoji': '🧊🚜',
    //   'category': 'vehicle',
    //   'url':  '/sounds/ice_rink_refrig.mp3',
    // },
    // {
    //   'id': 'hellfire_screams',
    //   'title': 'Hell',
    //   'emoji': '😈🔥',
    //   'category': 'other',
    //   'url':  '/sounds/hellfire_screams.mp3',
    // },
  ]